print('physics ready before init', KaptanPhysics.isReady())

local function expect_error(label, fn)
    local ok = pcall(fn)
    print(label, not ok)
end

KaptanPhysics.setUnitsPerMeter(64)
KaptanPhysics.setSubsteps(2)
KaptanPhysics.setTickRate(60)
KaptanPhysics.init()

print('physics ready after init', KaptanPhysics.isReady())

KaptanPhysics.setGravity(0, 0)
local gx, gy = KaptanPhysics.getGravity()
print('gravity', gx, gy)
print('substeps', KaptanPhysics.getSubsteps())
print('tick rate', KaptanPhysics.getTickRate())
print('units per meter', KaptanPhysics.getUnitsPerMeter())
expect_error('invalid tick rate rejected', function()
    KaptanPhysics.setTickRate(1001)
end)
print('debug draw before set', KaptanPhysics.isDebugDraw())
KaptanPhysics.setDebugDraw(true)
print('debug draw after set', KaptanPhysics.isDebugDraw())
KaptanPhysics.setDebugDraw(false)
print('debug draw after clear', KaptanPhysics.isDebugDraw())

local CATEGORY_PLAYER = 1 << 0
local CATEGORY_ENEMY = 1 << 1
local CATEGORY_WALL = 1 << 2

local body = KaptanPhysicsBody.new(KaptanPhysicsBody.DYNAMIC)
body:setTag('player')
print('body valid after create', body:isValid())
print('body id after create', body:getId() > 0)
print('body type after create', body:getType())
print('body tag after set', body:getTag())

local circle = body:addCircle(12)
local box = body:addBox(24, 32)
local rounded_box = body:addBox(24, 32, 4)
local capsule = body:addCapsule(16, 40, 8)
local polygon = body:addPolygon({ -12, -8, 12, -8, 0, 14 })
local sensor = body:addCircle(8, { sensor = true, sensorEvents = true })
print('circle valid after create', circle:isValid())
print('circle id after create', circle:getId() > 0)
print('box valid after create', box:isValid())
print('rounded box valid after create', rounded_box:isValid())
print('capsule valid after create', capsule:isValid())
print('polygon valid after create', polygon:isValid())
print('sensor valid after create', sensor:isValid())
print('sensor is sensor', sensor:isSensor())
print('sensor events enabled', sensor:isSensorEvents())

box:setDensity(2)
box:setFriction(0.25)
box:setRestitution(0.5)
box:setCategory(CATEGORY_ENEMY)
box:setMask(CATEGORY_PLAYER | CATEGORY_WALL)
box:setGroup(-1)
box:setContactEvents(true)
box:setHitEvents(true)
box:setTag('enemy')
expect_error('invalid density rejected', function()
    box:setDensity(-1)
end)
expect_error('invalid friction rejected', function()
    box:setFriction(-1)
end)
expect_error('invalid restitution rejected', function()
    box:setRestitution(-1)
end)
expect_error('invalid rounded box radius rejected', function()
    body:addBox(10, 10, 6)
end)
expect_error('invalid capsule radius rejected', function()
    body:addCapsule(10, 20, 6)
end)

local event_body = KaptanPhysicsBody.new(KaptanPhysicsBody.DYNAMIC)
event_body:setPos(10, 20)
local event_shape = event_body:addBox(10, 10, { contactEvents = true, sensorEvents = true })
event_shape:setTag('event-box')
local sensor_body = KaptanPhysicsBody.new(KaptanPhysicsBody.STATIC)
sensor_body:setPos(10, 20)
local event_sensor = sensor_body:addCircle(20, { sensor = true, sensorEvents = true })
event_sensor:setTag('event-sensor')
KaptanPhysics.step(1 / 60)
local contact_events = KaptanPhysics.getContactEvents()
local sensor_events = KaptanPhysics.getSensorEvents()
print('contact events after overlap', #contact_events)
print('sensor events after overlap', #sensor_events)
print('contact events after poll clear', #KaptanPhysics.getContactEvents())
print('sensor events after poll clear', #KaptanPhysics.getSensorEvents())
if contact_events[1] then
    print('first contact event kind', contact_events[1].kind)
    print('first contact shape valid', contact_events[1].shapeA:isValid(), contact_events[1].shapeB:isValid())
end
if sensor_events[1] then
    print('first sensor event kind', sensor_events[1].kind)
    print('first sensor shape valid', sensor_events[1].sensor:isValid(), sensor_events[1].visitor:isValid())
end

local negative_sensor_body = KaptanPhysicsBody.new(KaptanPhysicsBody.DYNAMIC)
negative_sensor_body:setPos(1000, 0)
local negative_sensor = negative_sensor_body:addCircle(20, { sensor = true, sensorEvents = true })
negative_sensor:setTag('negative-sensor')
local negative_visitor_body = KaptanPhysicsBody.new(KaptanPhysicsBody.DYNAMIC)
negative_visitor_body:setPos(1100, 0)
local negative_visitor = negative_visitor_body:addCircle(8)
negative_visitor:setTag('negative-visitor')
KaptanPhysics.step(1 / 60)
KaptanPhysics.getSensorEvents()
negative_sensor_body:setPos(1100, 0)
KaptanPhysics.step(1 / 60)
local negative_sensor_events = KaptanPhysics.getSensorEvents()
print('sensor events without visitor opt-in', #negative_sensor_events)
negative_sensor_body:destroy()
negative_visitor_body:destroy()
KaptanPhysics.step(1 / 60)
KaptanPhysics.getSensorEvents()

local dynamic_sensor_body = KaptanPhysicsBody.new(KaptanPhysicsBody.DYNAMIC)
dynamic_sensor_body:setPos(1200, 0)
local dynamic_sensor = dynamic_sensor_body:addCircle(20, { sensor = true, sensorEvents = true })
dynamic_sensor:setTag('dynamic-sensor')
local solid_visitor_body = KaptanPhysicsBody.new(KaptanPhysicsBody.DYNAMIC)
solid_visitor_body:setPos(1300, 0)
local solid_visitor = solid_visitor_body:addCircle(8, { sensorEvents = true })
solid_visitor:setTag('solid-visitor')
KaptanPhysics.step(1 / 60)
KaptanPhysics.getSensorEvents()
dynamic_sensor_body:setPos(1300, 0)
KaptanPhysics.step(1 / 60)
local dynamic_sensor_events = KaptanPhysics.getSensorEvents()
print('dynamic sensor events with visitor opt-in', #dynamic_sensor_events)
if dynamic_sensor_events[1] then
    print('dynamic sensor event kind', dynamic_sensor_events[1].kind)
    print('dynamic sensor visitor tag', dynamic_sensor_events[1].visitor:getTag())
end
dynamic_sensor_body:destroy()
solid_visitor_body:destroy()
KaptanPhysics.step(1 / 60)
KaptanPhysics.getSensorEvents()

local queried_shapes = KaptanPhysics.queryAABB(10, 20, 64, 64, { mask = CATEGORY_ENEMY })
local ray_hit = KaptanPhysics.raycast(-40, 0, 40, 0, { mask = CATEGORY_ENEMY })
print('query aabb enemy hits', #queried_shapes)
print('raycast enemy hit', ray_hit ~= nil)
if ray_hit then
    print('raycast shape valid', ray_hit.shape:isValid())
    print('raycast shape tag', ray_hit.shape:getTag())
end

print('box density', box:getDensity())
print('box friction', box:getFriction())
print('box restitution', box:getRestitution())
print('box category', box:getCategory())
print('box mask', box:getMask())
print('box group', box:getGroup())
print('box contact events', box:isContactEvents())
print('box hit events', box:isHitEvents())
print('box tag', box:getTag())

circle:destroy()
print('circle valid after destroy', circle:isValid())

body:setPos(10, 20)
body:setRot(45)
body:setVelocity(30, 40)
body:setAngularVelocity(90)
body:applyForce(1000000, 0)
body:applyImpulse(1000000, 0)
body:applyTorque(1000000)
body:applyAngularImpulse(1000000)
KaptanPhysics.step(1 / 60)
body:setLinearDamping(0.5)
body:setAngularDamping(0.25)
body:setBullet(true)

local x, y = body:getPos()
local vx, vy = body:getVelocity()
print('body pos', x, y)
print('body rot', body:getRot())
print('body velocity', vx, vy)
print('body impulse changed velocity', vx > 30)
print('body angular velocity', body:getAngularVelocity())
print('body impulse changed angular velocity', body:getAngularVelocity() > 90)
print('body linear damping', body:getLinearDamping())
print('body angular damping', body:getAngularDamping())

body:setFixedRotation(true)
print('body fixed rotation', body:isFixedRotation())
print('body bullet', body:isBullet())
print('body enabled before disable', body:isEnabled())

body:setEnabled(false)
print('body enabled after disable', body:isEnabled())
body:setEnabled(true)
print('body enabled after enable', body:isEnabled())

body:setType(KaptanPhysicsBody.KINEMATIC)
print('body type after set', body:getType())

body:destroy()
print('body valid after destroy', body:isValid())
print('box valid after body destroy', box:isValid())
print('sensor valid after body destroy', sensor:isValid())
event_body:destroy()
sensor_body:destroy()
print('event shape valid after body destroy', event_shape:isValid())
print('event sensor valid after body destroy', event_sensor:isValid())

local cleared_body = KaptanPhysicsBody.new(KaptanPhysicsBody.STATIC)
local cleared_shape = cleared_body:addBox(10, 10)
print('cleared body valid before clear', cleared_body:isValid())
print('cleared shape valid before clear', cleared_shape:isValid())

KaptanPhysics.clear()
print('physics ready after clear', KaptanPhysics.isReady())
print('cleared body valid after clear', cleared_body:isValid())
print('cleared shape valid after clear', cleared_shape:isValid())

KaptanPhysics.destroy()
print('physics ready after destroy', KaptanPhysics.isReady())
