print('animation once', KaptanAnimation.ONCE)
print('animation loop', KaptanAnimation.LOOP)
print('animation ping pong', KaptanAnimation.PING_PONG)
print('animation constants ordered', KaptanAnimation.ONCE < KaptanAnimation.LOOP and KaptanAnimation.LOOP < KaptanAnimation.PING_PONG)

local function expect_error(label, fn)
    local ok = pcall(fn)
    print(label, not ok)
end

print('ease linear midpoint', KaptanEase.sample(KaptanEase.LINEAR, 0.5))
print('ease step before end', KaptanEase.sample(KaptanEase.STEP, 0.5))
print('ease step at end', KaptanEase.sample(KaptanEase.STEP, 1))
print('ease in quad midpoint', KaptanEase.sample(KaptanEase.IN_QUAD, 0.5))
print('ease out quad midpoint', KaptanEase.sample(KaptanEase.OUT_QUAD, 0.5))
print('ease clamps low', KaptanEase.sample(KaptanEase.LINEAR, -1))
print('ease clamps high', KaptanEase.sample(KaptanEase.LINEAR, 2))
print('ease constants ordered', KaptanEase.LINEAR < KaptanEase.IN_OUT_BACK)
expect_error('invalid ease rejected', function()
    KaptanEase.sample(9999, 0.5)
end)

local curve = KaptanAnimationCurve.new()
print('curve empty count', curve:getKeyCount())
print('curve empty duration', curve:getDuration())
print('curve empty sample', curve:sample(0.5))
curve:addKey(1, 100)
print('curve one key sample', curve:sample(0.5))
curve:addKey(0, 0, KaptanEase.IN_QUAD)
curve:addKey(2, 200)
print('curve sorted count', curve:getKeyCount())
print('curve duration', curve:getDuration())
print('curve clamped before', curve:sample(-1))
print('curve eased midpoint', curve:sample(0.5))
print('curve linear midpoint', curve:sample(1.5))
print('curve clamped after', curve:sample(3))
curve:removeKey(2)
print('curve count after remove', curve:getKeyCount())
print('curve sample after remove', curve:sample(1))
curve:clear()
print('curve count after clear', curve:getKeyCount())
expect_error('invalid key time rejected', function()
    curve:addKey(-1, 0)
end)
expect_error('invalid key index rejected', function()
    curve:removeKey(1)
end)

local vec2_curve = KaptanVec2Curve.new()
local vx, vy = vec2_curve:sample(0.5)
print('vec2 empty sample', vx, vy)
vec2_curve:addKey(1, 100, 200)
vx, vy = vec2_curve:sample(0.5)
print('vec2 one key sample', vx, vy)
vec2_curve:addKey(0, 0, 0, KaptanEase.OUT_QUAD)
vec2_curve:addKey(2, 200, 400)
print('vec2 sorted count', vec2_curve:getKeyCount())
print('vec2 duration', vec2_curve:getDuration())
vx, vy = vec2_curve:sample(0.5)
print('vec2 eased midpoint', vx, vy)
vx, vy = vec2_curve:sample(1.5)
print('vec2 linear midpoint', vx, vy)
vec2_curve:removeKey(2)
print('vec2 count after remove', vec2_curve:getKeyCount())
vx, vy = vec2_curve:sample(1)
print('vec2 sample after remove', vx, vy)
vec2_curve:clear()
print('vec2 count after clear', vec2_curve:getKeyCount())
expect_error('invalid vec2 key time rejected', function()
    vec2_curve:addKey(-1, 0, 0)
end)
expect_error('invalid vec2 key index rejected', function()
    vec2_curve:removeKey(1)
end)
