print('animation once', KaptanAnimation.ONCE)
print('animation loop', KaptanAnimation.LOOP)
print('animation ping pong', KaptanAnimation.PING_PONG)
print('animation constants ordered', KaptanAnimation.ONCE < KaptanAnimation.LOOP and KaptanAnimation.LOOP < KaptanAnimation.PING_PONG)

local function expect_error(label, fn)
    local ok = pcall(fn)
    print(label, not ok)
end

print('ease linear midpoint', KaptanEase.sample(KaptanEase.LINEAR, 0.5))
print('ease step before end', KaptanEase.sample(KaptanEase.STEP, 0.5))
print('ease step at end', KaptanEase.sample(KaptanEase.STEP, 1))
print('ease in quad midpoint', KaptanEase.sample(KaptanEase.IN_QUAD, 0.5))
print('ease out quad midpoint', KaptanEase.sample(KaptanEase.OUT_QUAD, 0.5))
print('ease clamps low', KaptanEase.sample(KaptanEase.LINEAR, -1))
print('ease clamps high', KaptanEase.sample(KaptanEase.LINEAR, 2))
print('ease constants ordered', KaptanEase.LINEAR < KaptanEase.IN_OUT_BACK)
expect_error('invalid ease rejected', function()
    KaptanEase.sample(9999, 0.5)
end)

local curve = KaptanAnimationCurve.new()
print('curve empty count', curve:getKeyCount())
print('curve empty duration', curve:getDuration())
print('curve empty sample', curve:sample(0.5))
curve:addKey(1, 100)
print('curve one key sample', curve:sample(0.5))
curve:addKey(0, 0, KaptanEase.IN_QUAD)
curve:addKey(2, 200)
print('curve sorted count', curve:getKeyCount())
print('curve duration', curve:getDuration())
print('curve clamped before', curve:sample(-1))
print('curve eased midpoint', curve:sample(0.5))
print('curve linear midpoint', curve:sample(1.5))
print('curve clamped after', curve:sample(3))
curve:removeKey(2)
print('curve count after remove', curve:getKeyCount())
print('curve sample after remove', curve:sample(1))
curve:clear()
print('curve count after clear', curve:getKeyCount())
expect_error('invalid key time rejected', function()
    curve:addKey(-1, 0)
end)
expect_error('invalid key index rejected', function()
    curve:removeKey(1)
end)
