print('animation once', KaptanAnimation.ONCE)
print('animation loop', KaptanAnimation.LOOP)
print('animation ping pong', KaptanAnimation.PING_PONG)
print('animation constants ordered', KaptanAnimation.ONCE < KaptanAnimation.LOOP and KaptanAnimation.LOOP < KaptanAnimation.PING_PONG)

local function expect_error(label, fn)
    local ok = pcall(fn)
    print(label, not ok)
end

print('ease linear midpoint', KaptanEase.sample(KaptanEase.LINEAR, 0.5))
print('ease step before end', KaptanEase.sample(KaptanEase.STEP, 0.5))
print('ease step at end', KaptanEase.sample(KaptanEase.STEP, 1))
print('ease in quad midpoint', KaptanEase.sample(KaptanEase.IN_QUAD, 0.5))
print('ease out quad midpoint', KaptanEase.sample(KaptanEase.OUT_QUAD, 0.5))
print('ease clamps low', KaptanEase.sample(KaptanEase.LINEAR, -1))
print('ease clamps high', KaptanEase.sample(KaptanEase.LINEAR, 2))
print('ease constants ordered', KaptanEase.LINEAR < KaptanEase.IN_OUT_BACK)
expect_error('invalid ease rejected', function()
    KaptanEase.sample(9999, 0.5)
end)
