print('debug build', KaptanEnvironment.isDebugBuild())
print('debug build type', type(KaptanEnvironment.isDebugBuild()))
print('fps counter before', KaptanEnvironment.isFPSCounterEnabled())
KaptanEnvironment.setFPSCounterEnabled(true)
print('fps counter after enable', KaptanEnvironment.isFPSCounterEnabled())
KaptanEnvironment.setFPSCounterEnabled(false)
print('fps counter after disable', KaptanEnvironment.isFPSCounterEnabled())
print('frame profiling before', KaptanEnvironment.isFrameProfiling())
KaptanEnvironment.setFrameProfiling(true)
print('frame profiling after enable', KaptanEnvironment.isFrameProfiling())
local profile = KaptanEnvironment.getFrameProfile()
print('frame profile table', type(profile), type(profile.total), type(profile.lastRender))
print('frame profile percentiles', type(profile.total.p95Ms), type(profile.total.p99Ms))
KaptanEnvironment.resetFrameProfile()
KaptanEnvironment.setFrameProfiling(false)
print('frame profiling after disable', KaptanEnvironment.isFrameProfiling())
print('gc logging before', KaptanEnvironment.isLuaGCLogging())
KaptanEnvironment.setLuaGCLogging(true)
print('gc logging after enable', KaptanEnvironment.isLuaGCLogging())

local count = collectgarbage('count')
print('gc count type', type(count))
collectgarbage('collect')

KaptanEnvironment.setLuaGCLogging(false)
print('gc logging after disable', KaptanEnvironment.isLuaGCLogging())
collectgarbage('collect')
