print('debug build', KaptanEnvironment.isDebugBuild())
print('debug build type', type(KaptanEnvironment.isDebugBuild()))
print('fps counter before', KaptanEnvironment.isFPSCounterEnabled())
KaptanEnvironment.setFPSCounterEnabled(true)
print('fps counter after enable', KaptanEnvironment.isFPSCounterEnabled())
KaptanEnvironment.setFPSCounterEnabled(false)
print('fps counter after disable', KaptanEnvironment.isFPSCounterEnabled())
print('gc logging before', KaptanEnvironment.isLuaGCLogging())
KaptanEnvironment.setLuaGCLogging(true)
print('gc logging after enable', KaptanEnvironment.isLuaGCLogging())

local count = collectgarbage('count')
print('gc count type', type(count))
collectgarbage('collect')

KaptanEnvironment.setLuaGCLogging(false)
print('gc logging after disable', KaptanEnvironment.isLuaGCLogging())
collectgarbage('collect')
